name: project_x
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  json_annotation: ^4.8.1
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.0.1
  firebase_auth: ^4.19.2
  go_router: ^13.2.5
  email_validator: ^2.1.17
  rxdart: ^0.27.7
  loader_overlay: ^4.0.0
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true