name: project_x
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  email_validator: ^2.1.17
  firebase_app_check: ^0.2.2+5
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.0.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.5
  golden_toolkit: ^0.15.0
  http: ^1.2.1
  image_picker: ^1.1.1
  json_annotation: ^4.8.1
  loader_overlay: ^4.0.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  rxdart: ^0.27.7



dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  uses-material-design: true
