// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELxUyRNCo8bDRFmapzteKpr1JorPP4YY',
    appId: '1:1004062037286:web:368c7cd6ee8707f0639de7',
    messagingSenderId: '1004062037286',
    projectId: 'projectxtdk',
    authDomain: 'projectxtdk.firebaseapp.com',
    storageBucket: 'projectxtdk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPit96mrvf9WjI9CrRRUhPfc7SOOBTJAI',
    appId: '1:1004062037286:android:b51b43dd0fdbb8ab639de7',
    messagingSenderId: '1004062037286',
    projectId: 'projectxtdk',
    storageBucket: 'projectxtdk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1L8afg4yUX0iKc-TUj-YG-z03FpRpxS4',
    appId: '1:1004062037286:ios:ed51ded959b299c0639de7',
    messagingSenderId: '1004062037286',
    projectId: 'projectxtdk',
    storageBucket: 'projectxtdk.appspot.com',
    iosBundleId: 'kz.tohatdk.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoOLO3gyn1-FdPIb-RHug4OqeoPZ3TwtE',
    appId: '1:667791985478:ios:060e5d4cdb122075423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
    iosBundleId: 'kz.tohawow.cleanarch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1hEZu2DnNIEkfAs_mUEqBUgS-CECqWA',
    appId: '1:667791985478:web:8e2c186b01c88efb423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    authDomain: 'pushnotitutorial-75506.firebaseapp.com',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
    measurementId: 'G-SDW8H4KSTL',
  );
}
