// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvd05G4Fvqjqo2kBvpFz0-kcC0u5uZXdo',
    appId: '1:11200755384:web:f13f20d6b495928cde664d',
    messagingSenderId: '11200755384',
    projectId: 'projectx-1fc9d',
    authDomain: 'projectx-1fc9d.firebaseapp.com',
    storageBucket: 'projectx-1fc9d.appspot.com',
    measurementId: 'G-VW00NQS6ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDop4iQWP3Ao7pKGY1A_54AYRpGAp0xREc',
    appId: '1:11200755384:android:a075461c65f39df0de664d',
    messagingSenderId: '11200755384',
    projectId: 'projectx-1fc9d',
    storageBucket: 'projectx-1fc9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT9gj21dLk_zXhmHI2tXNAgfs95m1kNME',
    appId: '1:11200755384:ios:fe17a8863f6e490fde664d',
    messagingSenderId: '11200755384',
    projectId: 'projectx-1fc9d',
    storageBucket: 'projectx-1fc9d.appspot.com',
    iosBundleId: 'kz.tohatdk.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT9gj21dLk_zXhmHI2tXNAgfs95m1kNME',
    appId: '1:11200755384:ios:fe17a8863f6e490fde664d',
    messagingSenderId: '11200755384',
    projectId: 'projectx-1fc9d',
    storageBucket: 'projectx-1fc9d.appspot.com',
    iosBundleId: 'kz.tohatdk.projectx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1hEZu2DnNIEkfAs_mUEqBUgS-CECqWA',
    appId: '1:667791985478:web:8e2c186b01c88efb423347',
    messagingSenderId: '667791985478',
    projectId: 'pushnotitutorial-75506',
    authDomain: 'pushnotitutorial-75506.firebaseapp.com',
    storageBucket: 'pushnotitutorial-75506.appspot.com',
    measurementId: 'G-SDW8H4KSTL',
  );
}
