name: Project Check
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  AnalyzeAndBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: flutter test
      - name: Build
        run: flutter build apk --split-per-abi
